# Generated by Django 3.1.3 on 2022-02-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
