# Generated by Django 3.1.3 on 2022-02-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
